autocmd ColorScheme * highlight ExtraWhitespace ctermbg=lightblue guibg=lightblue
highlight link MaybeExtraWhitespace NONE
let s:hilightws=0

autocmd BufWritePost .vimrc source %

"Formatting
syntax on
if &term=~'linux' 
	set background=light
	"colorscheme summerfruit256
else
    "if has("gui_running")
	set background=light
	"colorscheme desert256
	"colorscheme summerfruit256
	"set gfn=Inconsolata-g\ 9
    set t_Co=256
endif
set nu!

" Color scheme
" ! mkdir -p ~/.vim/colors && cd ~/.vim/colors && wget -O wombat256mod.vim http://www.vim.org/scripts/download_script.php?src_id=13400
set t_Co=256
color wombat256mod
      
" Type kj to get out of insert mode!
inoremap kj <Esc>

" control jikl (akin to wasd) will switch panes
nnoremap <C-j> <C-w>h
nnoremap <C-l> <C-w>l
nnoremap <C-i> <C-w>k
nnoremap <C-k> <C-w>j



" NOTE THAT CONTROL + ; doesn't work (google it)
" move cursor when insert mode
" imap <C-;> <C-o>;
" imap <C-j> <C-o>j
" imap <C-k> <C-o>k
" imap <C-l> <C-o>l

" get rid of Thanks for flying Vim title
set title 
set titleold="" 
set titlestring=VIM:\ %F 

" backspace compatibility
set bs=2

"turn on wild menu for tab command completion
set wildmenu

" turn ruler on to show position
set ruler



" install pathogen: https://github.com/tpope/vim-pathogen
" install NERDtree: https://github.com/scrooloose/nerdtree


execute pathogen#infect()

"NERDTREE stuff
map <C-n> :NERDTreeToggle<CR>
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif " close vim if only nerdtree is left



" abbreviations for misspellings
abbr hte the
abbr teh the



" disable until you get practice with jkl;
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>

set scrolloff=5 " keep at least 5 lines visible on either side of cursor

set noerrorbells visualbell t_vb=

" Quickly set comma or semicolon at the end of the string
inoremap ,, <End>,
inoremap ;; <End>;
au FileType python inoremap :: <End>:

set ttyfast

" Don't redraw while executing macros (good performance config)
set lazyredraw

set cursorline          " highlight current line
set incsearch           " search as characters are entered
filetype indent on      " load FileType-specific indent files

" ENABLE USE OF MOUSE (SCROLL, SELECT, CURSOR PLACEMENT)
" set mouse=a

noremap l j
noremap k k
noremap ; l " shift hjkl over to jkl; and switch up and down
noremap j h

" map space to : to speed things up
nnoremap <Space> :

" Alt+l,k to drag lines up and down through putty
nnoremap l :m+<CR>==
nnoremap k :m-2<CR>==
inoremap l <Esc>:m+<CR>==gi
inoremap k <Esc>:m-2<CR>==gi
vnoremap l :m'>+<CR>gv=gv
vnoremap k :m-2<CR>gv=gv

"remap VIM 0 to first non-blank character
map 0 ^

" show the status line always
set laststatus=2


" format of statusline
set statusline=
set statusline=%t       "tail of the filename
set statusline+=%h      "help file flag
set statusline+=\ %#error# " START ERROR COLOR
set statusline+=%m      "modified flaga
set statusline+=%r      "read only flags
set statusline+=%*      " END COLORR
set statusline+=\ %y      "filetype
set statusline+=\ \[%{strftime('%I:%M%p\ \%a\ %b\ %d,\ %Y')}\]
set statusline+=\ %{getcwd()}
set statusline+=%=      "left/right separator
set statusline+=%c,     "cursor column
set statusline+=%l/%L   "cursor line/total lines
set statusline+=\ %P    "percent through file

" spell
map <F5> :setlocal spell! spelllang=en_us<CR>

" nnoremap <Enter> o<Esc>


" F6 executes gnuplot, python, C, C++ code by compiling and running
au BufEnter,BufNew *.{gp,p} map <buffer> <F6> <ESC> :w <kEnter> :!gnuplot % <kEnter>
autocmd FileType python nnoremap <F6> :w <bar> exec '!python '.shellescape('%')<CR>
autocmd FileType c nnoremap <F6> :w <bar> exec '!gcc '.shellescape('%').' -o '.shellescape('%:r').'.exe && ./'.shellescape('%:r') . '.exe'<CR>
autocmd FileType cpp nnoremap <F6> :w <bar> exec '!g++ '.shellescape('%').' -o '.shellescape('%:r').'.exe && ./'.shellescape('%:r') . '.exe'<CR>
" put printf template into code if using c++ and type PF in insert mode
autocmd FileType cpp inoremap PF printf("\n",);<Esc>=0f\i

noremap <Leader>wn :call WhiteSpace()<CR>

match MaybeExtraWhitespace /\s\+\%#\@<!$/
au InsertEnter * match MaybeExtraWhitespace /\s\+\%#\@<!$/
au InsertLeave * match MaybeExtraWhitespace /\s\+\%#\@<!$/

function! WhiteSpace()
	if s:hilightws
		highlight link MaybeExtraWhitespace NONE
		let s:hilightws = 0
		echo "Whitespace Highlighting On"
	else
		highlight link MaybeExtraWhitespace ExtraWhitespace
		let s:hilightws = 1
		echo "Whitespace Highlighting Off"
	endif
endfunction


""This autocmd changes the window-local current directory to be the same as the
""directory of the current file. It fails silently to prevent error messages
""when you edit files via ftp or new files. It works better in some cases
""because the autocmd is not nested, and will therefore not fire when switching
""buffers via another autocmd. It will also work in older versions of Vim or
""versions compiled without the 'autochdir' option. Note, however, that there
""is no easy way to test for this autocmd in a script like there is for the
""'autochdir' option.
set autochdir

"escape to clear highlighting

set tabstop=4
set shiftwidth=4
set softtabstop=4
set smarttab
set expandtab

nnoremap <F3> :set tabstop=2<CR>:set shiftwidth=2<CR>:set softtabstop=2<CR>
nnoremap <F4> :set tabstop=4<CR>:set shiftwidth=4<CR>:set softtabstop=4<CR>

"Set title of window to file name
set title

if has("autocmd")
	filetype plugin indent on
else
	set autoindent
endif

set showmatch
set matchtime=3
set incsearch
set hlsearch
"Ignores case for searches
set ignorecase
"case-sensitive if search contains an uppercase character
set smartcase


"Remember previous buffer session
exec 'set viminfo=%,' . &viminfo

"Auto-indent and tab width
"set ai
"set softtabstop=2
"set shiftwidth=2

"let python_highlight_all = 1

"set grepprg=grep\ -nH\ $*

"In insert mode, C-BS to delete previous word, and C-DEL to delete next
imap <C-BS> <C-W>
imap <C-DEL> <ESC>ldei

"Cut and Paste to System Clipboard
nmap <C-A-v> "+p
imap <C-A-v> <C-R>+
vmap <C-A-c> "+y

"Sets F2 to enable and disable line numeration
nnoremap <F2> :set nonumber!<CR>:set foldcolumn=0<CR>

set backup
set backupdir=~/.vim/

:hi MatchParen cterm=none ctermbg=black ctermfg=white
"set cryptmethod=blowfish
